title: "Example project of relation extraction"
description: "This example project shows how to implement a spaCy component with a custom Machine Learning model."

# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  annotations: "assets/annotations.jsonl"
  annotations_test: "assets/annotations_test.jsonl"
  config: "configs/rel_config.cfg"
  train: "data/train.spacy"
  dev: "data/dev.spacy"
  test: "data/test.spacy"
  ner_model: "../ner_component/training/model-best"
  trained_model: "training/model-best"
  script_data: "scripts/rel_parse_data.py"
  script_pipeline: "scripts/rel_pipeline.py"

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["scripts", "configs", "assets", "data", "training"]

# Assets that should be downloaded or available in the directory. You can replace
# this with your own input data.
assets:
    - dest: ${vars.annotations}
      description: "Gold-standard REL annotations created with Prodigy"
    - dest: ${vars.annotations_test}
      description: "Gold-standard REL annotations created with Prodigy for testing the model"

workflows:
  all_cpu:
    - data_cpu
    - train_cpu
  all_gpu:
    - data_gpu
    - train_gpu


# Project commands, specified in a style similar to CI config files (e.g. Azure
# pipelines). The name is the command name that lets you trigger the command
# via "spacy project run [command] [path]". The help message is optional and
# shown when executing "spacy project run [optional command] [path] --help".
commands:
  - name: "data_cpu"
    help: "Parse the gold-standard annotations from the Prodigy annotations."
    script:
      - "python ./scripts/rel_parse_data.py ${vars.annotations} ${vars.train} ${vars.dev} 0.2 0 ${vars.ner_model} "
      - "python ./scripts/rel_parse_data.py ${vars.annotations_test} ${vars.test} .\ 0 0 ${vars.ner_model}"
    deps:
      - ${vars.annotations}
      - ${vars.annotations_test}
      - ${vars.script_data}
      - ${vars.script_pipeline}
    outputs:
      - ${vars.train}
      - ${vars.dev}
      - ${vars.test}

  - name: "data_gpu"
    help: "Parse the gold-standard annotations from the Prodigy annotations."
    script:
      - "python ./scripts/rel_parse_data.py ${vars.annotations} ${vars.train} ${vars.dev} 0.2 1 ${vars.ner_model}"
      - "python ./scripts/rel_parse_data.py ${vars.annotations_test} ${vars.test} .\ 0 1 ${vars.ner_model}"
    deps:
      - ${vars.annotations}
      - ${vars.annotations_test}
      - ${vars.script_data}
      - ${vars.script_pipeline}
    outputs:
      - ${vars.train}
      - ${vars.dev}
      - ${vars.test}

  - name: "train_cpu"
    help: "Train the REL model on the CPU and evaluate on the dev corpus."
    script:
      - "python -m spacy train ${vars.config} --output training --paths.train ${vars.train} --paths.dev ${vars.dev} --paths.ner_model ${vars.ner_model} -c ./scripts/rel_reader.py"
    deps:
      - ${vars.config}
      - ${vars.train}
      - ${vars.dev}
    outputs:
      - ${vars.trained_model}

  - name: "train_gpu"
    help: "Train the REL model on the GPU and evaluate on the dev corpus."
    script:
      - "python -m spacy train ${vars.config} --output training --paths.train ${vars.train} --paths.dev ${vars.dev} --paths.ner_model ${vars.ner_model} -c scripts/rel_reader.py --gpu-id 0"
    deps:
      - ${vars.config}
      - ${vars.train}
      - ${vars.dev}
    outputs:
      - ${vars.trained_model}

  - name: "eval_cpu"
    help: "Evaluate the REL model on the CPU"
    script:
      - "python ./scripts/rel_eval.py ${vars.test} 0 ${vars.trained_model}"
    deps:
      - ${vars.test}
      - ${vars.trained_model}

  - name: "eval_gpu"
    help: "Evaluate the REL model on the GPU"
    script:
      - "python ./scripts/rel_eval.py ${vars.test} 1 ${vars.trained_model}"
    deps:
      - ${vars.test}
      - ${vars.trained_model}

  







